//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMyRDP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FollowMyRDP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///REM The following directory is for .NET 2.0
        ///set DOTNETFX2=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319
        ///set PATH=%PATH%;%DOTNETFX2%
        ///
        ///echo Installing FollowMeService...
        ///echo ---------------------------------------------------
        ///InstallUtil /i FollowMyRDP.exe REM Sender_Mail Recipient_Mail Sender_Password
        ///echo ---------------------------------------------------
        ///echo Done.
        ///pause.
        /// </summary>
        internal static string InstallService {
            get {
                return ResourceManager.GetString("InstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///REM The following directory is for .NET 2.0
        ///set DOTNETFX2=%SystemRoot%\Microsoft.NET\Framework\v2.0.50727
        ///set PATH=%PATH%;%DOTNETFX2%
        ///
        ///echo Uninstalling MyService...
        ///echo ---------------------------------------------------
        ///InstallUtil /u MyService.exe
        ///echo ---------------------------------------------------
        ///echo Done.
        /// </summary>
        internal static string UnInstallService {
            get {
                return ResourceManager.GetString("UnInstallService", resourceCulture);
            }
        }
    }
}
